// src/App.tsx
import { lazy, Suspense, useState, useRef, useCallback } from "react";
import type { ConnectionProfile, LocalShellId } from "./lib/types";
import ConnectionScreen from "./components/ConnectionScreen";
import "./App.css";

type AppView = "connect" | "terminal";

const MainView = lazy(() => import("./components/MainView"));

function App() {
  const [view, setView] = useState<AppView>("connect");
  const [initialSessionId, setInitialSessionId] = useState<string | null>(null);
  const [initialProfile, setInitialProfile] = useState<ConnectionProfile | null>(null);
  const [initialLocalShell, setInitialLocalShell] = useState<LocalShellId | null>(null);
  const [glitching, setGlitching] = useState(false);
  const glitchRef = useRef<HTMLDivElement>(null);

  const handleConnected = (
    sid: string,
    _pid: string,
    prof: ConnectionProfile,
  ) => {
    setInitialSessionId(sid);
    setInitialProfile(prof);
    setInitialLocalShell(null);
    setView("terminal");
  };

  const handleLocalTerminal = useCallback((shellType: LocalShellId) => {
    setInitialSessionId(null);
    setInitialProfile(null);
    setInitialLocalShell(shellType);
    setView("terminal");
  }, []);

  const handleDisconnected = useCallback(() => {
    setGlitching(true);
    setTimeout(() => {
      setGlitching(false);
      setInitialSessionId(null);
      setInitialProfile(null);
      setInitialLocalShell(null);
      setView("connect");
    }, 400);
  }, []);

  return (
    <div className="app">
      {view === "connect" && (
        <ConnectionScreen onConnected={handleConnected} onLocalTerminal={handleLocalTerminal} />
      )}
      {view === "terminal" && (initialLocalShell || (initialSessionId && initialProfile)) && (
        <div ref={glitchRef} className={glitching ? "view-glitch-out" : ""} style={{ height: "100%", width: "100%" }}>
          <Suspense fallback={<div className="app-loading">LINKING TERMINAL...</div>}>
            <MainView
              initialSessionId={initialSessionId}
              initialProfile={initialProfile}
              initialLocalShell={initialLocalShell}
              onDisconnected={handleDisconnected}
            />
          </Suspense>
        </div>
      )}
    </div>
  );
}

export default App;

// src/App.svelte
<script lang="ts">
  import type { ConnectionProfile, LocalShellId } from "./lib/types";
  import ConnectionScreen from "./components/ConnectionScreen.svelte";

  type AppView = "connect" | "terminal";

  let view = $state<AppView>("connect");
  let initialSessionId = $state<string | null>(null);
  let initialProfile = $state<ConnectionProfile | null>(null);
  let initialLocalShell = $state<LocalShellId | null>(null);
  let glitching = $state(false);

  function handleConnected(sid: string, _pid: string, prof: ConnectionProfile) {
    initialSessionId = sid;
    initialProfile = prof;
    initialLocalShell = null;
    view = "terminal";
  }

  function handleLocalTerminal(shellType: LocalShellId) {
    initialSessionId = null;
    initialProfile = null;
    initialLocalShell = shellType;
    view = "terminal";
  }

  function handleDisconnected() {
    glitching = true;
    setTimeout(() => {
      glitching = false;
      initialSessionId = null;
      initialProfile = null;
      initialLocalShell = null;
      view = "connect";
    }, 400);
  }
</script>

<div class="app">
  {#if view === "connect"}
    <ConnectionScreen onConnected={handleConnected} onLocalTerminal={handleLocalTerminal} />
  {/if}
  {#if view === "terminal" && (initialLocalShell || (initialSessionId && initialProfile))}
    <div class={glitching ? "view-glitch-out" : ""} style="height: 100%; width: 100%;">
      {#await import("./components/MainView.svelte")}
        <div class="app-loading">LINKING TERMINAL...</div>
      {:then { default: MainView }}
        <MainView
          {initialSessionId}
          {initialProfile}
          {initialLocalShell}
          onDisconnected={handleDisconnected}
        />
      {/await}
    </div>
  {/if}
</div>
